language: ruby
sudo: required
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.11.2

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:setup
env:
  global:
  - RAILS_ENV=test
